# Blueprint: Mukamghor
# Docs: https://render.com/docs/deploy-php-laravel-docker

databases:
  - name: mukamghor-db
    plan: free
    databaseName: mukamghor
    user: mukamghor

services:
  - type: web
    name: mukamghor
    runtime: docker
    plan: free
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: mukamghor-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mukamghor-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mukamghor-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mukamghor-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mukamghor-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://mukamghor.onrender.com
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
