# Blueprint: Mukamghor

databases:
  - name: olys-bazar-db
    plan: free
    databaseName: olys_bazar
    user: olys_bazar

services:
  - type: web
    name: mukamghor
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: olys-bazar-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://mukamghor.onrender.com
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
